// <auto-generated />
using System;
using Complete.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Complete.Migrations
{
    [DbContext(typeof(RestoraniContext))]
    [Migration("20250528105946_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Complete.Models.Grad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojStanovnika")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Povrsina")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("Complete.Models.Jelo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("DaLiJeJelo")
                        .HasColumnType("bit");

                    b.Property<int>("KalorijskaVrednost")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RestoranID")
                        .HasColumnType("int");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RestoranID");

                    b.ToTable("Jelo");
                });

            modelBuilder.Entity("Complete.Models.JeloSastojak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("JeloID")
                        .HasColumnType("int");

                    b.Property<double>("Kolicina")
                        .HasColumnType("float");

                    b.Property<int?>("SastojakID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("JeloID");

                    b.HasIndex("SastojakID");

                    b.ToTable("Recept");
                });

            modelBuilder.Entity("Complete.Models.Magacin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Kolicina")
                        .HasColumnType("float");

                    b.Property<int?>("RestoranID")
                        .HasColumnType("int");

                    b.Property<int?>("SastojakID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RestoranID");

                    b.HasIndex("SastojakID");

                    b.ToTable("Magacin");
                });

            modelBuilder.Entity("Complete.Models.Restoran", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojOcena")
                        .HasColumnType("int");

                    b.Property<int?>("GradID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prihodi")
                        .HasColumnType("float");

                    b.Property<double>("Rashodi")
                        .HasColumnType("float");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("ZbirOcena")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("GradID");

                    b.ToTable("Restorani");
                });

            modelBuilder.Entity("Complete.Models.Sastojak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RokTrajanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Sastojci");
                });

            modelBuilder.Entity("Complete.Models.TipHrane", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("RestoranFK")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RestoranFK")
                        .IsUnique()
                        .HasFilter("[RestoranFK] IS NOT NULL");

                    b.ToTable("TipHrane");
                });

            modelBuilder.Entity("Complete.Models.Jelo", b =>
                {
                    b.HasOne("Complete.Models.Restoran", "Restoran")
                        .WithMany("Meni")
                        .HasForeignKey("RestoranID");

                    b.Navigation("Restoran");
                });

            modelBuilder.Entity("Complete.Models.JeloSastojak", b =>
                {
                    b.HasOne("Complete.Models.Jelo", "Jelo")
                        .WithMany("Sastojci")
                        .HasForeignKey("JeloID");

                    b.HasOne("Complete.Models.Sastojak", "Sastojak")
                        .WithMany("Jela")
                        .HasForeignKey("SastojakID");

                    b.Navigation("Jelo");

                    b.Navigation("Sastojak");
                });

            modelBuilder.Entity("Complete.Models.Magacin", b =>
                {
                    b.HasOne("Complete.Models.Restoran", "Restoran")
                        .WithMany("Magacin")
                        .HasForeignKey("RestoranID");

                    b.HasOne("Complete.Models.Sastojak", "Sastojak")
                        .WithMany("Magacin")
                        .HasForeignKey("SastojakID");

                    b.Navigation("Restoran");

                    b.Navigation("Sastojak");
                });

            modelBuilder.Entity("Complete.Models.Restoran", b =>
                {
                    b.HasOne("Complete.Models.Grad", "Grad")
                        .WithMany("Restorani")
                        .HasForeignKey("GradID");

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("Complete.Models.TipHrane", b =>
                {
                    b.HasOne("Complete.Models.Restoran", "Restoran")
                        .WithOne("TipHrane")
                        .HasForeignKey("Complete.Models.TipHrane", "RestoranFK");

                    b.Navigation("Restoran");
                });

            modelBuilder.Entity("Complete.Models.Grad", b =>
                {
                    b.Navigation("Restorani");
                });

            modelBuilder.Entity("Complete.Models.Jelo", b =>
                {
                    b.Navigation("Sastojci");
                });

            modelBuilder.Entity("Complete.Models.Restoran", b =>
                {
                    b.Navigation("Magacin");

                    b.Navigation("Meni");

                    b.Navigation("TipHrane");
                });

            modelBuilder.Entity("Complete.Models.Sastojak", b =>
                {
                    b.Navigation("Jela");

                    b.Navigation("Magacin");
                });
#pragma warning restore 612, 618
        }
    }
}
