// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SplitSync.Data;

#nullable disable

namespace SplitSync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SplitSync.Entities.Anketa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasStarted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFinished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GroupId");

                    b.ToTable("ankete", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.AnketaAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnketaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnketaId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AnketaId")
                        .IsUnique();

                    b.ToTable("anketa_answers", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.AnketaAnswerOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnketaAnswerId")
                        .HasColumnType("bigint");

                    b.Property<long>("AnketaOptionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ocena")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnketaAnswerId");

                    b.HasIndex("AnketaOptionId");

                    b.HasIndex("AnketaAnswerId", "AnketaOptionId")
                        .IsUnique();

                    b.ToTable("anketa_answer_options", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.AnketaOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnketaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnketaId");

                    b.ToTable("anketa_options", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GrupaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Poruka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("SentById")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GrupaId");

                    b.HasIndex("SentById");

                    b.ToTable("chat", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.Dogadjaj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<long>("GrupaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Lokacija")
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("VremeDogadjaja")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GrupaId");

                    b.ToTable("dogadjaji", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.DogadjajGlas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DogadjajId")
                        .HasColumnType("bigint");

                    b.Property<int>("GlasOption")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DogadjajId")
                        .IsUnique();

                    b.ToTable("dogadjaji_glasovi", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.EmailConfirmation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("email_confirmations", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultValuta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.GroupInvitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("InvitedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("InvitedUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("InvitedUserId");

                    b.ToTable("group_invitations", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.GroupsUsers", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("JoinedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("groups_users", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.PasswordReset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("password_resets", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.Racun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<double>("Iznos")
                        .HasColumnType("double precision");

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("GroupId");

                    b.ToTable("racuni", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.RacunItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("DeoRacuna")
                        .HasColumnType("double precision");

                    b.Property<double>("Iznos")
                        .HasColumnType("double precision");

                    b.Property<long>("RacunId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RacunId");

                    b.HasIndex("UserId");

                    b.ToTable("racun_items", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.ShoppingListaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NabavioUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NabavljenoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TrazenoUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("TrazioUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("NabavioUserId");

                    b.HasIndex("TrazioUserId");

                    b.ToTable("shopping_lista_items", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("bytea");

                    b.Property<string>("SlikaExtension")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SplitSync.Entities.Anketa", b =>
                {
                    b.HasOne("SplitSync.Entities.User", "Creator")
                        .WithMany("KreiraneAnkete")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.Group", "Group")
                        .WithMany("Ankete")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SplitSync.Entities.AnketaAnswer", b =>
                {
                    b.HasOne("SplitSync.Entities.Anketa", "Anketa")
                        .WithMany("AnketaAnswers")
                        .HasForeignKey("AnketaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.User", "User")
                        .WithMany("AnketaAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anketa");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitSync.Entities.AnketaAnswerOption", b =>
                {
                    b.HasOne("SplitSync.Entities.AnketaAnswer", "AnketaAnswer")
                        .WithMany("AnketaAnswerOptions")
                        .HasForeignKey("AnketaAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.AnketaOption", "AnketaOption")
                        .WithMany("AnketaAnswerOptions")
                        .HasForeignKey("AnketaOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnketaAnswer");

                    b.Navigation("AnketaOption");
                });

            modelBuilder.Entity("SplitSync.Entities.AnketaOption", b =>
                {
                    b.HasOne("SplitSync.Entities.Anketa", "Anketa")
                        .WithMany("AnketaOptions")
                        .HasForeignKey("AnketaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anketa");
                });

            modelBuilder.Entity("SplitSync.Entities.Chat", b =>
                {
                    b.HasOne("SplitSync.Entities.Group", "Grupa")
                        .WithMany("Chats")
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.User", "SentBy")
                        .WithMany("Chats")
                        .HasForeignKey("SentById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupa");

                    b.Navigation("SentBy");
                });

            modelBuilder.Entity("SplitSync.Entities.Dogadjaj", b =>
                {
                    b.HasOne("SplitSync.Entities.User", "Creator")
                        .WithMany("CreatedDogadjaji")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.Group", "Grupa")
                        .WithMany("Dogadjaji")
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Grupa");
                });

            modelBuilder.Entity("SplitSync.Entities.DogadjajGlas", b =>
                {
                    b.HasOne("SplitSync.Entities.Dogadjaj", "Dogadjaj")
                        .WithMany("Glasovi")
                        .HasForeignKey("DogadjajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.User", "User")
                        .WithMany("Glasovi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogadjaj");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitSync.Entities.GroupInvitation", b =>
                {
                    b.HasOne("SplitSync.Entities.Group", "Group")
                        .WithMany("GroupInvitations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.User", "InvitedByUser")
                        .WithMany("GroupInvites")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.User", "InvitedUser")
                        .WithMany("GroupInvitations")
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");
                });

            modelBuilder.Entity("SplitSync.Entities.GroupsUsers", b =>
                {
                    b.HasOne("SplitSync.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.User", "User")
                        .WithMany("MemberGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitSync.Entities.Racun", b =>
                {
                    b.HasOne("SplitSync.Entities.User", "Creator")
                        .WithMany("RacuniKaoKreator")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SplitSync.Entities.Group", "Group")
                        .WithMany("Racuni")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SplitSync.Entities.RacunItem", b =>
                {
                    b.HasOne("SplitSync.Entities.Racun", "Racun")
                        .WithMany("Items")
                        .HasForeignKey("RacunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.User", "User")
                        .WithMany("RacunItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Racun");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitSync.Entities.ShoppingListaItem", b =>
                {
                    b.HasOne("SplitSync.Entities.Group", "Grupa")
                        .WithMany("ShoppingListaItems")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplitSync.Entities.User", "Nabavio")
                        .WithMany("NabavljeniItemi")
                        .HasForeignKey("NabavioUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SplitSync.Entities.User", "Trazio")
                        .WithMany("TrazeniItemi")
                        .HasForeignKey("TrazioUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupa");

                    b.Navigation("Nabavio");

                    b.Navigation("Trazio");
                });

            modelBuilder.Entity("SplitSync.Entities.Anketa", b =>
                {
                    b.Navigation("AnketaAnswers");

                    b.Navigation("AnketaOptions");
                });

            modelBuilder.Entity("SplitSync.Entities.AnketaAnswer", b =>
                {
                    b.Navigation("AnketaAnswerOptions");
                });

            modelBuilder.Entity("SplitSync.Entities.AnketaOption", b =>
                {
                    b.Navigation("AnketaAnswerOptions");
                });

            modelBuilder.Entity("SplitSync.Entities.Dogadjaj", b =>
                {
                    b.Navigation("Glasovi");
                });

            modelBuilder.Entity("SplitSync.Entities.Group", b =>
                {
                    b.Navigation("Ankete");

                    b.Navigation("Chats");

                    b.Navigation("Dogadjaji");

                    b.Navigation("GroupInvitations");

                    b.Navigation("Members");

                    b.Navigation("Racuni");

                    b.Navigation("ShoppingListaItems");
                });

            modelBuilder.Entity("SplitSync.Entities.Racun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SplitSync.Entities.User", b =>
                {
                    b.Navigation("AnketaAnswers");

                    b.Navigation("Chats");

                    b.Navigation("CreatedDogadjaji");

                    b.Navigation("Glasovi");

                    b.Navigation("GroupInvitations");

                    b.Navigation("GroupInvites");

                    b.Navigation("KreiraneAnkete");

                    b.Navigation("MemberGroups");

                    b.Navigation("NabavljeniItemi");

                    b.Navigation("RacunItems");

                    b.Navigation("RacuniKaoKreator");

                    b.Navigation("TrazeniItemi");
                });
#pragma warning restore 612, 618
        }
    }
}
